"""empty message

Revision ID: 349ea302b8f0
Revises: 8fd5827fa52a
Create Date: 2019-05-17 21:04:01.502967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349ea302b8f0'
down_revision = '8fd5827fa52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='cases')
    op.add_column('inventory', sa.Column('expiration', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('expiration_period', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'expiration_period')
    op.drop_column('inventory', 'expiration')
    op.create_index('name', 'cases', ['name'], unique=True)
    # ### end Alembic commands ###
