"""empty message

Revision ID: 4a8b48232b5f
Revises: 
Create Date: 2019-05-11 20:50:31.679816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a8b48232b5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'items', ['name'])
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.TEXT(), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'active')
    op.drop_constraint(None, 'items', type_='unique')
    # ### end Alembic commands ###
