"""empty message

Revision ID: 5e647ed78984
Revises: 4631bafa1241
Create Date: 2019-05-13 16:46:05.672793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e647ed78984'
down_revision = '4631bafa1241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('code', sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, 'inventory', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_column('inventory', 'code')
    # ### end Alembic commands ###
