"""empty message

Revision ID: 8fd5827fa52a
Revises: 58b8f78bc78b
Create Date: 2019-05-17 18:00:45.248017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd5827fa52a'
down_revision = '58b8f78bc78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'items', ['name'], unique=True)
    # ### end Alembic commands ###
