"""empty message

Revision ID: 902e6563f1f1
Revises: c06620d266bb
Create Date: 2019-05-18 18:38:58.364213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902e6563f1f1'
down_revision = 'c06620d266bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('expiration_period', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'expiration_period')
    # ### end Alembic commands ###
